export default function Head() {
  return (
    <>
      <title>Charlytoc's portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link precedence='default' rel="preconnect" href="https://fonts.googleapis.com/"/>
      <link precedence='default' rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link precedence='default' href="https://fonts.googleapis.com/css2?family=Encode+Sans+Condensed:wght@500&family=Montserrat&display=swap" rel="stylesheet"></link>
      <link precedence='default' href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet"></link>
    </>
  )
}
